Repository project-studying-dotnet/Streetcode-Server-August-2025, pull requests merged in 2025-08, with the labels that each got.

#33 Test/issue #10/added tests for Mediatr/News
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/News/CreateNewsTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/News/DeleteNewsTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/News/GetAllNewsTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/News/GetNewsAndLinksByUrlTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/News/GetNewsByIdTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/News/GetNewsByUrlTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/News/SortedByDateTimeTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/News/UpdateNewsTests.cs
  Streetcode/Streetcode.XUnitTest/Streetcode.XUnitTest.csproj
Labels: tests

#36 Refactor/7: Add explicit recurringJobId to Program.cs
  Streetcode/Streetcode.WebApi/Program.cs
Labels: sonar, refactor

#47 Create docker-compose.yml
  docker-compose.yml
Labels: enhancement

#57 Test/16/write unit tests for meadiat r/toponyms
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Toponyms/GetAll/GetAllToponymsHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Toponyms/GetById/GetToponymByIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Toponyms/GetByStreetCodeId/GetToponymsByStreetcodeIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/Streetcode.XUnitTest.csproj
Labels: tests

#66 Test/14/write tests for mediatr email
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Email/SendEmailHandlerTests.cs
Labels: tests

#72 Feature/68/implement create streetcode api endpoint
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Create/StreetcodeCreateCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Create/StreetcodeCreateHandler.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/StreetcodeController.cs
  Streetcode/Streetcode.WebApi/appsettings.IntegrationTests.json
  Streetcode/Streetcode.WebApi/appsettings.Local.json
  Streetcode/Streetcode.WebApi/appsettings.json
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/StreetCode/Streetcode/Create/StreetcodeCreateHandlerTest.cs
Labels: task

#80 Model validation pipeline, validators and test. Issues #52 and #53
  Streetcode/Streetcode.BLL/ApplicationAssembly.cs
  Streetcode/Streetcode.BLL/Behaviors/ResultFactory.cs
  Streetcode/Streetcode.BLL/Behaviors/ValidationBehavior.cs
  Streetcode/Streetcode.BLL/MediatR/Newss/Create/CreateNewsCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Newss/Create/CreateNewsHandler.cs
  Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
  Streetcode/Streetcode.BLL/Validators/AdditionalContent/Coordinate/CreateCoordinateCommandValidator.cs
  Streetcode/Streetcode.BLL/Validators/AdditionalContent/Coordinate/StreetcodeCoordinateDTOValidator.cs
  Streetcode/Streetcode.BLL/Validators/AdditionalContent/Coordinate/StreetcodeCoordinateUpdateDTOValidator.cs
  Streetcode/Streetcode.BLL/Validators/AdditionalContent/Coordinate/UpdateCoordinateCommandValidator.cs
  Streetcode/Streetcode.BLL/Validators/Email/EmailDTOValidator.cs
  Streetcode/Streetcode.BLL/Validators/Email/SendEmailCommandValidator.cs
  Streetcode/Streetcode.BLL/Validators/Helpers/ValidationHelper.cs
  Streetcode/Streetcode.BLL/Validators/Media/Audio/AudioFileBaseCreateDTOValidator.cs
  Streetcode/Streetcode.BLL/Validators/Media/Audio/CreateAudioCommandValidator.cs
  Streetcode/Streetcode.BLL/Validators/Media/FileBaseCreateDTOValidator.cs
  Streetcode/Streetcode.BLL/Validators/Media/Image/CreateImageCommandValidator.cs
  Streetcode/Streetcode.BLL/Validators/Media/Image/ImageFileBaseCreateDTOValidator.cs
  Streetcode/Streetcode.BLL/Validators/News/CreateNewsCommandValidator.cs
  Streetcode/Streetcode.BLL/Validators/News/NewsDTOValidator.cs
  Streetcode/Streetcode.BLL/Validators/News/UpdateNewsCommandValidator.cs
  Streetcode/Streetcode.BLL/Validators/Partners/CreatePartnerDTOValidator.cs
  Streetcode/Streetcode.BLL/Validators/Partners/CreatePartnerQueryValidator.cs
  Streetcode/Streetcode.BLL/Validators/Partners/CreatePartnerSourceLinkDTOValidator.cs
  Streetcode/Streetcode.BLL/Validators/Partners/StreetcodeShortDTOValidator.cs
  Streetcode/Streetcode.BLL/Validators/Payment/CreateInvoiceCommandValidator.cs
  Streetcode/Streetcode.BLL/Validators/Team/Position/CreatePositionQueryValidator.cs
  Streetcode/Streetcode.BLL/Validators/Team/TeamMembersLinks/CreateTeamLinkQueryValidator.cs
  Streetcode/Streetcode.DAL/Enums/LogoType.cs
  Streetcode/Streetcode.WebApi/Controllers/NewsController.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.WebApi/Streetcode.WebApi.csproj
  Streetcode/Streetcode.XUnitTest/BLL/Validators/AdditionalContent/Coordinate/CreateCoordinateCommandValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/AdditionalContent/Coordinate/StreetcodeCoordinateDTOValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/AdditionalContent/Coordinate/StreetcodeCoordinateUpdateDTOValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/AdditionalContent/Coordinate/UpdateCoordinateCommandValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Email/EmailDTOValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Email/SendEmailCommandValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Helpers/ValidationHelperTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Media/Audio/AudioFileBaseCreateDTOValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Media/Audio/CreateAudioCommandValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Media/Image/CreateImageCommandValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Media/Image/ImageFileBaseCreateDTOValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/News/CreateNewsCommandValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/News/NewsDTOValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/News/UpdateNewsCommandValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Other/ResultFactoryTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Other/ValidationBehaviorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Partners/CreatePartnerDTOValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Partners/CreatePartnerQueryValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Partners/CreatePartnerSourceLinkDTOValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Partners/StreetcodeShortDTOValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Payment/CreateInvoiceCommandValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Team/Position/CreatePositionQueryValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Team/TeamMembersLinks/CreateTeamLinkQueryValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/Streetcode.XUnitTest.csproj
Labels: enhancement
