Repository project-studying-dotnet/Streetcode-Server-August-2025, pull requests merged in 2025-09, with the labels that each got.

#113 Add dtos mapping validator
  Streetcode/Streetcode.BLL/DTO/AdditionalContent/Coordinates/Update/StreetcodeCoordinateUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Locations/MapPointDTO.cs
  Streetcode/Streetcode.BLL/DTO/Locations/MapPointResponseDTO.cs
  Streetcode/Streetcode.BLL/DTO/Locations/Update/MapPointUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/Create/StreetcodeCreateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/StreetcodeCreateUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Toponyms/StreetcodeToponymCreateUpdateDTO.cs
  Streetcode/Streetcode.BLL/Mapping/AdditionalContent/Coordinates/StreetcodeCoordinateProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Locations/MapPointProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/StreetcodeProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Toponyms/StreetcodeToponymProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Toponyms/ToponymProfile.cs
  Streetcode/Streetcode.BLL/Validators/Streetcode/Toponyms/StreetcodeToponymValidator.cs
  Streetcode/Streetcode.WebApi/Program.cs
Labels: enhancement

#117 Feature/116/add art gallery crud
  Streetcode/Streetcode.BLL/DTO/ArtGallery/StreetcodeArtSlideCreateUpdateDTO.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Create/StreetcodeCreateHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/StreetCode/Streetcode/Create/StreetcodeCreateHandlerTest.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/StreetCode/Streetcode/Update/UpdateStreetcodeTests.cs
Labels: enhancement

#123 Add get endpoints for art gallery
  Streetcode/Streetcode.BLL/MediatR/ArtGallery/GetSlidesByStreetcodeId/GetArtSlidesByStreetcodeIdHandler.cs
  Streetcode/Streetcode.BLL/MediatR/ArtGallery/GetSlidesByStreetcodeId/GetArtSlidesByStreetcodeIdQuery.cs
  Streetcode/Streetcode.BLL/MediatR/ArtGallery/GetSlidesCountByStreetcodeId/GetSlidesCountByStreetcodeIdHandler.cs
  Streetcode/Streetcode.BLL/MediatR/ArtGallery/GetSlidesCountByStreetcodeId/GetSlidesCountByStreetcodeIdQuery.cs
  Streetcode/Streetcode.BLL/MediatR/Media/StreetcodeArt/GetByStreetcodeId/GetStreetcodeArtByStreetcodeIdHandler.cs
  Streetcode/Streetcode.DAL/Entities/Media/Images/ImageDetails.cs
  Streetcode/Streetcode.WebApi/Controllers/ArtGallery/StreetcodeArtSlideController.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/ArtGallery/GetSlidesByStreetcodeId/GetArtSlidesByStreetcodeIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/ArtGallery/GetSlidesCountByStreetcodeId/GetSlidesCountByStreetcodeIdHandlerTests.cs
Labels: enhancement

#133 Feature/121/add create update methods mediator toponyms mappoints
  Streetcode/Streetcode.BLL/DTO/Streetcode/Create/StreetcodeCreateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
  Streetcode/Streetcode.BLL/Mapping/Locations/MapPointProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/StreetcodeProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Create/StreetcodeCreateHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
  Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/StreetCode/Streetcode/Update/UpdateStreetcodeTests.cs
Labels: task

#153 Feature/134/mappoint api controller full crud functionality
  Streetcode/Streetcode.BLL/MediatR/Locations/Delete/DeleteMapPointCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Locations/Delete/DeleteMapPointHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Locations/GetAll/GetAllMapPointsHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Locations/GetAll/GetAllMapPointsQuery.cs
  Streetcode/Streetcode.BLL/MediatR/Locations/Update/UpdateMapPointCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Locations/Update/UpdateMapPointsHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Partners/GetAll/GetAllPartnersQuery.cs
  Streetcode/Streetcode.WebApi/Controllers/Instagram/InstagramController.cs
  Streetcode/Streetcode.WebApi/Controllers/Locations/MapPointController.cs
Labels: task

#151 Fix/125/fix inconsistent fluent validation integration
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Create/CreateSourceLinkCategoryCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Create/CreateSourceLinkCategoryHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Update/UpdateSourceLinkCategoryCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Update/UpdateSourceLinkCategoryHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/StreetcodeCategoryContent/Create/CreateStreetcodeCategoryContentCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/StreetcodeCategoryContent/Create/CreateStreetcodeCategoryHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/StreetcodeCategoryContent/Update/UpdateStreetcodeCategoryContentCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/StreetcodeCategoryContent/Update/UpdateStreetcodeCategoryContentHandler.cs
  Streetcode/Streetcode.BLL/Validators/Source/SourceLinkCategory/CreateSourceLinkCategoryValidator.cs
  Streetcode/Streetcode.BLL/Validators/Source/SourceLinkCategory/UpdateSourceLinkCategoryValidator.cs
  Streetcode/Streetcode.BLL/Validators/Source/StreetcodeCategoryContent/CreateStreetcodeCategoryContentValidator.cs
  Streetcode/Streetcode.BLL/Validators/Source/StreetcodeCategoryContent/UpdateStreetcodeCategoryContentValidator.cs
  Streetcode/Streetcode.BLL/Validators/Streetcode/BaseStreetcodeValidator.cs
  Streetcode/Streetcode.BLL/Validators/Streetcode/CreateStreetcodeValidator.cs
  Streetcode/Streetcode.BLL/Validators/Streetcode/ImageDetails/ImageDetailsValidator.cs
  Streetcode/Streetcode.BLL/Validators/Streetcode/UpdateStreetcodeValidator.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Streetcode/BaseStreetcodeValidatorsTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Streetcode/CreateStreetcodeValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Streetcode/ImageDetails/ImageDetailsValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Streetcode/UpdateStreetcodeValidatorTests.cs
Labels: bug

#155 Finish task
  Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedTerm/Delete/DeleteRelatedTermCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedTerm/Delete/DeleteRelatedTermHandler.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/RelatedTermController.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/StreetCode/RelatedTerm/DeleteRelatedTermHandlerTest.cs
Labels: task

#156 Feature/implement crud operations for admin chronology block
  Streetcode/Streetcode.BLL/DTO/Timeline/TimelineItem/TimelineItemBaseDTO.cs
  Streetcode/Streetcode.BLL/Interfaces/Timeline/IHistoricalContextService.cs
  Streetcode/Streetcode.BLL/Mapping/Timeline/TimelineItemProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/HistoricalContext/Delete/DeleteHistoricalContextCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/HistoricalContext/Delete/DeleteHistoricalContextHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Create/CreateTimelineItemCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Create/CreateTimelineItemHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Delete/DeleteTimelineItemHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Delete/DeleteTimlineItemCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Update/UpdateTimelineItemHandler.cs
  Streetcode/Streetcode.BLL/Services/Timeline/HistoricalContextService.cs
  Streetcode/Streetcode.WebApi/Controllers/Timeline/HistoricalContextController.cs
  Streetcode/Streetcode.WebApi/Controllers/Timeline/TimelineItemController.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Timeline/HistoricalContext/DeleteHistoricalContextHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Timeline/TimelineItem/Create/CreateTimelineItemHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Timeline/TimelineItem/Delete/DeleteTimelineItemHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Timeline/TimelineItem/GetById/GetTimelineItemByIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Timeline/TimelineItem/Update/UpdateTimelineItemHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Services/HistoricalContextServiceTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Timeline/TimelineItem/CreateTimelineItemCommandValidatorTests.cs
Labels: user story

#160 Pull Request: Add Unit Tests for MediatR/Partners Handlers (Issue #11)
  Streetcode/Streetcode.BLL/AssemblyInfo.cs
  Streetcode/Streetcode.BLL/MediatR/Partners/GetById/GetPartnerByIdHandler.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Partners/CreatePartnersTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Partners/DeletePartnersTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Partners/GetAllPartnerShortTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Partners/GetAllPartnersTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Partners/GetByIdPartnersTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Partners/GetByStreetcodeIdPartnersTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Partners/UpdatePartnersTests.cs
Labels: tests

#188 Added user registartion and RevokeRefreshToken. Issue #85
  Streetcode/Streetcode.BLL/DTO/Users/RegisterUserDTO.cs
  Streetcode/Streetcode.BLL/DTO/Users/RegisterUserResponseDTO.cs
  Streetcode/Streetcode.BLL/Interfaces/Jwt/IJwtTokenService.cs
  Streetcode/Streetcode.BLL/Mapping/Users/UserProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserHandler.cs
  Streetcode/Streetcode.BLL/Services/JwtTokenService/JwtTokenService.cs
  Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
  Streetcode/Streetcode.BLL/Validators/Users/RegisterUserCommandValidator.cs
  Streetcode/Streetcode.BLL/Validators/Users/RegisterUserDTOValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Auth/AuthController.cs
  Streetcode/Streetcode.WebApi/Streetcode.WebApi.csproj
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Users/RegisterUserTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Services/JwtTokenServiceTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Users/RegisterUserCommandValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Users/RegisterUserDTOValidatorTests.cs
Labels: task

#168 Refactor/163/declare types in namespaces
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Email/SendEmailHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Team/TeamMembersLinks/CreateTeamLinkQueryValidatorTests.cs
Labels: sonar, refactor

#225 Feature/174/edit comments
  Streetcode/Streetcode.BLL/MediatR/Comments/Update/UpdateCommentCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Comments/Update/UpdateCommentHandler.cs
  Streetcode/Streetcode.BLL/Services/Timeline/HistoricalContextService.cs
  Streetcode/Streetcode.BLL/Validators/Comments/UpdateCommentCommandValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Comments/CommentController.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Comments/Update/UpdateCommentHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Services/HistoricalContextServiceTests.cs
  Streetcode/Streetcode.XUnitTest/BLL/Validators/Comments/UpdateCommentCommandValidatorTests.cs
Labels: requirement

#228 Added nested replies under comment and some adjustments to meet user reply requirements. Issues #212, #227
  Streetcode/Streetcode.BLL/DTO/Comments/CommentDTO.cs
  Streetcode/Streetcode.BLL/DTO/Users/UserCommentDTO.cs
  Streetcode/Streetcode.BLL/Mapping/Comments/CommentProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Comments/Create/CreateCommentHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Comments/GetByStreetcodeId/GetCommentsByStreetcodeIdHandler.cs
  Streetcode/Streetcode.DAL/Persistence/Migrations/20250914172204_MovedRefreshTokenToSeparateTable.cs
  Streetcode/Streetcode.DAL/Repositories/Interfaces/Comments/ICommentRepository.cs
  Streetcode/Streetcode.DAL/Repositories/Realizations/Comments/CommentRepository.cs
  Streetcode/Streetcode.WebApi/Controllers/Comments/CommentController.cs
  Streetcode/Streetcode.XUnitTest/BLL/MediatR/Comments/GetByStreetcodeId/GetCommentsByStreetcodeIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/Repositories/Realizations/Comments/CommentRepositoryTests.cs
  Streetcode/Streetcode.XUnitTest/Streetcode.XUnitTest.csproj
Labels: enhancement
